### ISSUE TITLE
How to type return value of `Column` reductions

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#158]
This is related to https://github.com/data-apis/dataframe-api/issues/155, but I'm opening a new issue to make sure it's not forgotten

Currently column reductions are typed to return `type`. But if we also use `type` to type arguments, such as `Column.from_sequence`, then they should probably be distinguished.

For example, I could pass `'float64'` to `Column.from_sequence`, but the return value of `column.mean()` wouldn't be `'float64'`, it would probably just be a Python 'float'.

I don't really know yet what the solution here is, will think about it, but I think we can do better

**Comment by rgommers** [comment]
(note: it should be `dtype` not `type` above)

I meant to revisit that - in `dataframe_object.py` we're using `Scalar` as the annotation for Python scalars. E.g.,:
```python
Scalar = TypeVar("Scalar")  # not further worked out, indicates any Python scalar type

def __eq__(self, other: DataFrame | Scalar) -> DataFrame:
```
Now of course when it's a return type the static typing should technically be overloads I think, rather than `dtype` or `Scalar`. But we don't want to clutter the spec itself with overloads probably, because those are pretty meaningless and verbose to the average reader.
