### ISSUE TITLE
Column.is_in

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#159]
In the last call it was brought up that perhaps we should add `Column.is_in`

This can be achieved with the existing Standard methods:
```python
result = column == values[0]
for value in values[1:]:
    if math.isnan(value):
        result |= column.isnan()
    elif value is namespace.null:
        result |= column.isnull()
    else:
        result |= column == value
```
so it really just be a convenience method. No objections to adding it anyway

**Comment by jorisvandenbossche** [comment]
Apart from convenience, an additional reason that many DataFrame libraries have a function like this is also because it can be much more performant with a custom implementation, compared to the generic code above. 

(also, your code needs a slight edit to support NaN/null as first value, so probably it would be easiest to start `result` with an all-False column)

**Comment by MarcoGorelli** [comment]
right, thanks - OK, I'll make a PR then, this probably needs to be included
