### ISSUE TITLE
Column.null instead of namespace.null ?

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#225]
We currently have two similar methods:
- `fill_nan`: only fill floating point NaN value
- `fill_null`: fill missing values, which may be implementation-dependent

For the second one, I think it (unfortunately) may also be column-dependent within a given implementation

pandas example:
- `NaT` represents missing values in datetime columns
- `NaN` represents missing values in its classical numpy dtypes
- `NA` represents missing values in nullable numpy / nullable pyarrow dtypes

So, what to do here? I can think of two things

## Solution 1

Only declare `NA` to be missing for the pandas implementation

For a classical numpy-backed column, `fill_null` would be a no-op.

This wouldn't be too big of an issue for `'float64'`, where you could fill nan values using `fill_nan`, but it would mean that a datetime column with `NaT` values just couldn't be filled

## Solution 2

Define `Column.null`. So, in pandas:
- for 'float64', Column.null would be `np.nan`
- for `'Float64'` / `'Float64[pyarrow]'`, `'Int64'`, etc., `Column.null` would be `pd.NA`
- for `'datetime64'`, `Column.null` would be `pd.NaT`

## Non-solutions

That `namespace.null` depends on the column which the namespace was extracted from.

I think this would have issues:
- it's possible to get `namespace` from `df.__dataframe_namespace`
- a dataframe typically has columns of different dtypes

**Comment by rgommers** [comment]
@MarcoGorelli I am not sure I understand the problem here. Say you have a column named `col`, and retrieved the namespace and called it `px`. Then the intended usage is `col.fill_nan(px.null)`. This works no matter what the dtype of `col` is. That inside the implementation, the `fill_nan` method may map `null` to NA/nan/NaT is not really relevant for the API design I'd think.

> a dataframe typically has columns of different dtypes

I don't understand what would go wrong here. `null` is the syntax, and all the semantics are well-defined.
