### ISSUE TITLE
Separate object for a dataframe colum? (is Series needed?)

### ISSUE THREAD

**Issue by datapythonista** [data-apis/dataframe-api#6]
Probably a bit early to the discussion, but I think this will need to be discussed eventually.

Is a separate object representing a single column needed? Like having Series, instead of just using one column DataFrame.

Having two separate objects, IMO adds a decent amount of complexity, both in the implementation and for the user. Whether this complexity is worth or not, I don't know. But I think this shouldn't be replicated from pandas without a discussion.

**Comment by SimonHeybrock** [comment]
Sorry for being late to the party: My comment https://github.com/data-apis/dataframe-api/issues/59#issuecomment-913641267 is related to this. Similar xarray, [scipp](https://scipp.github.io/) supports what we can think of as a higher-dimensional generalization of `Series` (`DataArray`) with more explicit indices (coordinates). I think when working with higher-dimensional data then working with these `Series`-like objects is more common than working with a "dict-of-series" (`DataFrame`).

I also note some discussion about mask-columns above. Scipp does this explicitly by attaching not just a `coords` dict to an array of data values, but also a `masks` dict. See https://scipp.github.io/user-guide/masking.html for an introduction to the concept.

If there is interest I'd be happy to talk in more detail about these aspects.

**Comment by rgommers** [comment]
It looks to me like there _may_ be a need for a separate column object - in the end that's what we needed in the interchange protocol as well - however the trick will then be to figure out how to add that without having a large set of duplicate APIs between column and dataframe objects.

**Comment by jbrockmendel** [comment]
What would `df.iloc[n]` give in this scenario?  It might avoid casting in mixed-dtype cases which code be nice.

**Comment by jbrockmendel** [comment]
> in what scenario?

```
df = pd.DataFrame({"A": [1], "B": [pd.Timestamp.now()]})
```

ATM `df.iloc[0]` gives an object-dtype Series.  IIUC in the proposal here `df.iloc[0]` would just return a view on `df`, so would not do any casting.

**Comment by jbrockmendel** [comment]
Is there a .dtypes?  and if so, what does it return if there is no Series?

**Comment by kkraus14** [comment]
> Is there a .dtypes? and if so, what does it return if there is no Series?

Please do not return a dataframe column for this information. This is a source of inconsistency for C++ and GPU backed dataframe implementations, where the dtypes are usually stored in the host side structure. In cuDF today for example, if someone calls the `.dtypes` method it returns a pandas Series as opposed to a cuDF series since it doesn't make sense for those to get copied to the GPU.

**Comment by rgommers** [comment]
A standard Python tuple or other container would probably make more sense than a Series object, but those also can't live on a GPU (and anyway, dtype is already stored on the host)? @kkraus14 is the API inherently problematic, or are you fine with it being a tuple and there needing to be synchronizations (I think?) when dtypes are used in control flow for example?

**Comment by jbrockmendel** [comment]
What if we had a Series but required very little of it API-wise.  Really just enough so that `frame.dtypes[col]` or `frame.max()[col]` makes sense

**Comment by rgommers** [comment]
Isn't `frame.dtypes[col]` better/equivalently spelled as `frame[col].dtype`?

For `frame.max()[col]` I may be missing your point, can you elaborate? It's a reduction; any reduction is still giving a dataframe back, so why is this different from `frame[col]`?

**Comment by jbrockmendel** [comment]
> Isn't frame.dtypes[col] better/equivalently spelled as frame[col].dtype?

That would require a discussion about what type `frame[col]` returns, which I'm trying to side-step for now.

> For frame.max()[col] I may be missing your point, can you elaborate? It's a reduction; any reduction is still giving a dataframe back, so why is this different from frame[col]?

It isn't obvious to me that any reduction gives a dataframe back.

**Comment by kkraus14** [comment]
> @kkraus14 is the API inherently problematic, or are you fine with it being a tuple and there needing to be synchronizations (I think?) when dtypes are used in control flow for example?

A tuple is good. Sorry, my point was that the information is already on the host in Python objects and you don't want to try to shove those into columns that may or may be typically backed by device memory.

**Comment by jorisvandenbossche** [comment]
If we want to consider this, I think it would be good if someone could investigate and list the potential impact on broadcasting and scalar behaviour in various situations, so we can think through those cases. 

Boolean filtering was already mentioned above (in numpy, boolean indexing with a 2D array instead of 1D doesn't work as you would expect for dataframes), but two other cases I am currently thinking of:

- Series is 1d, which impacts broadcasting rules in operations. Now, since standard broadcasting tries to match on the last dimension, in our case the columns, that might not be too problematic? (`df + s` also already matches on columns of df)
  - However, pandas complicates things doing column name alignment, which is another discussion, but might impact this one as well
  - If something like `df.mean()` gives a (1, n) shaped DataFrame, then `df / df.mean()` would work according to numpy broadcasting rules and for column label alignment, but in pandas we also align on row labels. So this would for pandas only work if we implement optional indexes, so a reduction can give a len-1 DataFrame without row index. 
- Related to the ``frame.max()[col]`` or `frame[col].max()` that Brock mentioned above: under the "everything DataFrame" idea, `df[col].max()` would give a 1-row 1-col DataFrame as result instead of a scalar? How would such a dataframe behave as a scalar? Or would the user be expected to explicitly convert this into a scalar? 
  - For example, a user doing `if df["col"].max() > 0: ...`, how would this work?

**Comment by shwina** [comment]
Are we opposed to `df["col"]` returning a `Column` (instead of an indexed "`Series`")?

**Comment by rgommers** [comment]
@shwina I think to answer that, we should have some idea of the methods on a new `Column`. I believe the main issue with `Series` was/is the large amount of duplication in methods/properties between it and `DataFrame`.

**Comment by jbrockmendel** [comment]
>  I believe the main issue with Series was/is the large amount of duplication in methods/properties between it and DataFrame.

I don't understand why that's a problem, especially if a lot of code can be shared.

**Comment by shwina** [comment]
@rgommers - yup, I totally understand we'd need to go through the work of defining an API for `Column` separate from `DataFrame`, but ultimately I really do believe that would be the best user experience.

> I believe the main issue with Series was/is the large amount of duplication in methods/properties between it and DataFrame.

I think the major issue with `Series` is that it needs to be both `array`-like and `DataFrame`-like at the same time. What we're calling `Column` here would be devoid of DataFrame semantics. Unfortunately, it can't be exactly an `array` either, as the latter does not support all the data types we want to support here.

**Comment by rgommers** [comment]
> I don't understand why that's a problem, especially if a lot of code can be shared.

API surface size does matter even if there are no differences in signatures or semantics (and I'm not sure that's even true?) imho, from a user perspective, a library maintainer perspective, and from a "this is a lot of work for us to standardize for little gain" perspective. That said, @shwina's point below is more important.

> I think the major issue with `Series` is that it needs to be both `array`-like and `DataFrame`-like at the same time.

Good point - yes, that sounds about right to me, that is the more important conceptual issue.

> Unfortunately, it can't be a true data-apis compliant `ndarray` either, as the latter does not support all the data types we want to support here.

There is nothing in the array API standard that says one cannot support extra dtypes, or add some extra functions/methods to support such dtypes. I think what you are getting at is more of an implementation issue, rather than an API one. Do you see anything API-wise that would not work? The main thing I can think of is semantics for nullable dtypes, which is unspecified.

Making `Column` adhere to the array API standard is related to gh-50. It would have a lot of benefits, like making it easy to support column input in libraries like SciPy.

**Comment by jbrockmendel** [comment]
My impression from today's call is that we are leaning towards having a Column object that would be 1D but not have a .index or .name, making it more array-like than Series-like.  There was discussion of missing-handling that sounded like that would distinguish it from an array-api object, but I didn't totally follow.

**Comment by rgommers** [comment]
> There was discussion of missing-handling that sounded like that would distinguish it from an array-api object, but I didn't totally follow.

I'm not sure it would necessarily prevent following the array API standard. However, when missing data is present, any functions that are not element-wise will have to have their semantics specified. That is something that's outside of the scope of the array API standard (because no array implementations actually support missing data). It's a tractable problem though, there are not that many functions that do need extra semantics. I think these are:
- reductions (`max`, `min`, `mean`, `prod`, `std`, `sum`, `var`)
- sorting, set and search functions (`sort`, `argsort`, `unique*`, `argmax`, `argmin`, `nonzero`, `where`)
- `all`, `any`
- linear algebra functions
- Fourier transform functions

**Comment by rgommers** [comment]
My sense is that for reductions, sort/set/search and `any`/`all`, the missing value semantics are mostly "ignore". Plus some corner cases like:
- if all values in a column being reduced over are NA, the result is NA (?),
- for sorting the output size should equal the input size, so missing values should be sorted to the beginning or end of the column (similar to `nan` handling)

And linear algebra and Fourier transforms should probably simply raise exceptions.

I'm curious if that kind of approach would work.

**Comment by MarcoGorelli** [comment]
We've gone ahead with adding `Column` to the spec, so I think this can now be closed, right?

Closing then, but please do let me know if I've misunderstood
