### ISSUE TITLE
Testing a `DataFrameObject` consumption from another dataframe library

### ISSUE THREAD

**Issue by iskode** [data-apis/dataframe-api#63]
One of the main usefulness of the interchangeable protocol is to consume a `DataFrameObject` from
other dataframe libraries:

`myDFLibrary.from_dataframe(anotherDFLibrary.__dataframe__())`

Currently, we can only write tests with `DataFrameObject` from the same library we are implementing the protocol in:

`myDFLibrary.from_dataframe(myDFLibrary.__dataframe__())`

In the case of `cudf` (GPU dataframe), we can't write tests for the scenario where a `DataFrameObject` is on the CPU like for pandas. This is a **very important use case of the protocol specifications to test** as it makes sure the device transfer is properly handled.

I don't how to go about it. The objective of this issue is to think collectively about a way to mock up these kinds of use cases. 
An example where mocking up is relatively simple, is testing `chunks` feature as `cudf` does not support it like pandas. To mock up chunks, we can create many `DataFrameObject` from chunks of few rows from a given `DataFrameObject`.

**Comment by rgommers** [comment]
We had a bit of discussion on this with a few people this week. @jreback brought up that it would be good to eventually have a central test repository where all-to-all testing can be done for the libraries supporting the protocol. Until that happens, testing against another implementation in Pandas can be done as an optional test dependency.

Mocking up a whole implementation is a little tricky, because it may be about as much work as a full implementation for one library. I assume that the cuDF test suite does already require Pandas? If so, it should be possible to use the Pandas implementation once that gets merged, and until that time either take a version of it that is monkey patched into Pandas, or just test outside of CI and wait.

Not completely ideal, but I suspect mocking in a way that tests (for example) actual device transfers is hard.

**Comment by kkraus14** [comment]
> I assume that the cuDF test suite does already require Pandas?

It does. We also have our own code for going from Pandas <--> cuDF that could be used for validation.

**Comment by iskode** [comment]
Thank you all for the precision.

**Comment by rgommers** [comment]
We now have a central repo where different implementations are tested against each other: https://github.com/data-apis/dataframe-interchange-tests. So I'll close this. Thanks @iskode
