### ISSUE TITLE
Restrictions on column labels

### ISSUE THREAD

**Issue by TomAugspurger** [data-apis/dataframe-api#7]
One of the uncontroversial points from https://github.com/pydata-apis/dataframe-api/issues/2 is that DataFrames have column labels / names. I'd like to discuss two specific points on this before merging the results into that issue.

1. What type can the column labels be? Should they be limited to just strings?
2. Do we require uniqueness of column labels?

I'm a bit unsure whether these are getting too far into the implementation side of things. Should we just take no stance on either of these?

---

My responses:

1. We should probably labels to be any type.

Operations like `crosstab` / `pivot` places a column from the input dataframe into the column labels of the output.

We'll need to be careful with how this interacts with the indexing API, since a label like the tuple `('my', 'label')` might introduce ambiguities (e.g. the full list of labels is `['my', 'label', ('my', 'label')]`.

Is it reasonable to require each label to be hashable? Pandas requires this, to facilitate lookup in a hashtable.

2. We cannot require uniqueness.

dataframes are commonly used to wrangle real-world data into shape, and real-world data is messy. If an implementation wants to ensure uniqueness (perhaps on a per-object basis) then is can offer that separately. But the API should at least allow for it.

**Comment by jbrockmendel** [comment]
Just checking, requiring unique all-string columns means "to satisfy the spec, you must support unique all-string columns", not "to satisfy the spec, you must support _only_ unique all-string columns", right?

**Comment by jbrockmendel** [comment]
so to be spec-compliant pandas would have to deprecate support for non-unique columns and non-string columns?

**Comment by rgommers** [comment]
> Saying "implementation X must support Y" seems reasonable. Continuing with "and it must not support Z" seems unnecessary and counterproductive.

Agreed - I think there are very few cases of this though. In general, we'd expect libraries to offer a superset of functionality of what's in a standard. So that means that if a user or downstream package author restricts themselves to the standardized set of APIs and to inputs that are supported, they have portable code. And if they go beyond it, they don't.

Maybe I was wrong above. It's possible for a library to support non-unique/non-string columns, as long as the behavior is compliant for any methods/functions in the standard. Additionally, it'd be good to have sane defaults outside of that, so for example all I/O routines and other standard ways of creating dataframes would default to producing unique string names. Otherwise it's too easy to write non-portable code. But then an explicit `.rename(['col1', 'col2', 42])` may be fine.

> f I apply the same reasoning to the description of arrays being contiguous, that means you're not _allowed_ to support strided arrays, so e.g. `df.iloc[::2]` would have to either be disallowed or make a copy?

No, that's certainly not intended. The copy is only necessary in `__dataframe__`, for interchange with another library.

**Comment by MarcoGorelli** [comment]
> if a user or downstream package author restricts themselves to the standardized set of APIs and to inputs that are supported, they have portable code. And if they go beyond it, they don't

this has generally been the guiding principle - so pandas need to forbid non-string column names, but anyone writing something like
```python
df = data.__dataframe_consortium_standard__()
df.assign((df.col('a') + df.col('b')).rename(1999))
```
can't expect the above to produce dataframe-agnostic code

I think the opening issue / question has been addressed then, so closing, but please let me know if I've misunderstood and I'll reopn
